\documentclass[11pt,]{problemset}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
    \setmainfont[]{IPAPMincho}
    \setsansfont[]{IPAPGothic}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage{hyperref}
\hypersetup{unicode=true,
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}

%%% Change title format to be more compact
\usepackage{titling}

% Create subtitle command for use in maketitle
\providecommand{\subtitle}[1]{
  \posttitle{
    \begin{center}\large#1\end{center}
    }
}

\setlength{\droptitle}{-2em}

  \title{}
    \pretitle{\vspace{\droptitle}}
  \posttitle{}
    \author{}
    \preauthor{}\postauthor{}
    \date{}
    \predate{}\postdate{}
  
\usepackage[ipa]{zxjafont}
\usepackage{sectsty}
\usepackage{tikz}
\usetikzlibrary{trees}
\usepackage{mathspec}
\usepackage{amsmath,amsthm}
\usepackage{amssymb,amsfonts}
\usepackage[all,arc]{xy}
\usepackage{enumerate}
\usepackage{mathrsfs}
\usepackage[margin=1in]{geometry}
\usepackage{thmtools}
\usepackage{verbatim}
\usepackage{xltxtra}
\XeTeXlinebreaklocale ``ja''
\XeTeXlinebreakskip=0pt plus 1pt
\XeTeXlinebreakpenalty=0
\setmainfont[]{IPAPMincho}
\setsansfont[]{IPAPGothic}
\usepackage{afterpage}
\sectionfont{\fontsize{12}{15}\selectfont}
\author{学籍番号:}
\course{疫学演習 2019-6-5 \& 2019-6-12}
\problemset{ }
\problem{ }
\collab{氏名:}

\begin{document}

\section{問題１：両群間計量データの平均値を比較する}

２００名の認知症患者を募集し，認識能力テスト(cognitive test,
COG)，及び脳萎縮の進行度 (brain atrophy,
脳体積の平均年間減少率，単位は\%)
の検査を全員に行った．COG，及び脳萎縮のデータは大きいほど認知症の進行度がより進んでいる．また，この２００名の参加者から採取した血液検体を利用して，ある遺伝子の変異の有無を検査した．このデータは以下の表でまとめた：

\bigskip
\begin{center}
\begin{tabular}{|l|l|l|l|l|}\hline
変数                     & \multicolumn{2}{c|}{遺伝変異あり (n = 50)}     & \multicolumn{2}{c|}{遺伝変異なし (n = 150)}   \\\hline
                       & \vtop{\hbox{\strut 平均値}\hbox{\strut (mean)}}&\vtop{\hbox{\strut  標準偏差}\hbox{\strut (standard deviation) }} & \vtop{\hbox{\strut 平均値}\hbox{\strut (mean)}}&\vtop{\hbox{\strut  標準偏差}\hbox{\strut (standard deviation) }} \\\hline
認識能力テスト，COG            & 69.2       & 9.0                       & 60.2       & 9.0                       \\
脳萎縮度, atrophy, \%/year & 0.67       & 0.21                      & 0.23       & 0.10                     \\\hline
\end{tabular}
\end{center}
\bigskip

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  帰無仮説を「遺伝子変異ありと変異なし両群の間に，COGの平均値は等しい」とする．上記のデータ及び適宜な方法を使って検定せよ．検定の結果を分かりやすく説明せよ．なお，分散が等しいと仮定できる場合，以下の式で両群の共通標準偏差が計算できる：
\end{enumerate}

\begin{equation}
  \label{eq:1}
S = \sqrt{\frac{(n_A - 1)S^2_A + (n_B - 1)S^2_B}{n_A + n_B -2}}
\end{equation}

\begin{itemize}
\tightlist
\item
  \(S_A:\) A群の標準偏差；
\item
  \(n_A:\) A群の人数；
\item
  \(S_B:\) B群の標準偏差；
\item
  \(n_B:\) B群の人数；
\item
  \(S:\) A群及びB群の共通標準偏差；
\item
  \(n_A + n_B -2:\) 分散が等しい時の自由度．
\end{itemize}

また，EZR で t 値，自由度 (degree of freedom)を使って P
値を計算する時，以下のコマンドを利用してください：

\begin{Shaded}
\begin{Highlighting}[]
\DecValTok{2}\OperatorTok{*}\KeywordTok{pt}\NormalTok{(t value, degree of freedom, }\DataTypeTok{lower=}\OtherTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\newpage
\vfill

\subsection{答え}

両群の標準偏差は 9.0 と推定され，分散が等しいと仮定できるから，Student
の t 検定を行う：

\[
T = \frac{\bar{X}_A - \bar{X}_B}{S\sqrt{1/n_A + 1/n_B}}
\]

公式(\ref{eq:1})により，共通分散/標準偏差を推定する： \[
\begin{aligned}
\because\;\;  S & = \sqrt{\frac{(n_A - 1)S^2_A + (n_B - 1)S^2_B}{n_A + n_B -2}} \\
\therefore\;\; S & =  \sqrt{\frac{(50 - 1)9^2 + (150 - 1)9^2}{50 + 150 -2}} = 9 \\
\Rightarrow\;\; T & = \frac{\bar{X}_A - \bar{X}_B}{S\sqrt{1/n_A + 1/n_B}} \\ 
                  & = \frac{69.2 - 60.2}{9\times\sqrt{1/50 + 1/150}} \\ 
                  & = \frac{9}{9\times0.1633} = 6.1237
\end{aligned}
\]

自由度 (degree of freedom)は \(n_A + n_B -2 = 198\)，P値の計算は EZR
を利用する：

\begin{Shaded}
\begin{Highlighting}[]
\DecValTok{2}\OperatorTok{*}\KeywordTok{pt}\NormalTok{(}\FloatTok{6.1237}\NormalTok{, }\DecValTok{198}\NormalTok{, }\DataTypeTok{lower=}\OtherTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 4.831141e-09
\end{verbatim}

\begin{center}\includegraphics[width=0.9\linewidth]{pic/tvaluepvalue00} \end{center}
\bigskip

\newpage
\vfill

以下のコードをRスクリプトに入力して，実行をクリックしてください．自分の検定結果とは一致するかを確認してください．

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{source}\NormalTok{(}\StringTok{"http://aoki2.si.gunma-u.ac.jp/R/src/my_t_test.R"}\NormalTok{, }\DataTypeTok{encoding=}\StringTok{"euc-jp"}\NormalTok{)}
\KeywordTok{my.t.test}\NormalTok{(}\DecValTok{50}\NormalTok{, }\FloatTok{69.2}\NormalTok{, }\FloatTok{9.0}\OperatorTok{^}\DecValTok{2}\NormalTok{, }\DecValTok{150}\NormalTok{, }\FloatTok{60.2}\NormalTok{, }\FloatTok{9.0}\OperatorTok{^}\DecValTok{2}\NormalTok{, }\DataTypeTok{var.equal=}\OtherTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  等分散を仮定した，二群の平均値の差の検定
## 
## data:  
## n1 = 50, mean1 = 69.2, variance1 = 81
## n2 = 150, mean2 = 60.2, variance2 = 81
## t = 6.1237, df = 198, p-value = 4.831e-09
\end{verbatim}

\begin{center}\includegraphics[width=0.9\linewidth]{pic/myttest01} \end{center}
\bigskip

\underline{手で計算した結果とは一致していると確認できる．}

この検定結果は「両群のCOG平均値が等しい」という帰無仮説を棄却するために非常に強い証拠を提供したと言える．

There is strong evidence against the null hypothesis that the means of
COG are the same in the two groups.

\newpage
\vfill

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  この患者データから，遺伝子変異ありとなしの群の間に脳萎縮度 (atrophy)
  の比較を 1. と同じ方法で検定してもよいか？どの検定方法を使えば 1.
  と同じ検定方法を使えるかどうかを判断できるを説明せよ．実際にこの検定方法を行ってください．
\end{enumerate}

なお，EZR で F 値，両群の分散，両群それぞれの自由度 (df) を使って P
値を計算する時に，以下のコマンドを利用してください：

\begin{Shaded}
\begin{Highlighting}[]
\DecValTok{2}\OperatorTok{*}\KeywordTok{pf}\NormalTok{(F value, df }\ControlFlowTok{in}\NormalTok{ group }\DecValTok{1}\NormalTok{, df }\ControlFlowTok{in}\NormalTok{ group }\DecValTok{2}\NormalTok{, }\DataTypeTok{lower=}\OtherTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\hypertarget{-1}{%
\subsection{答え}\label{-1}}

テーブルから両群の標準偏差はそれぞれ 0.21, 0.10 だと推定され，分散
(variance)
が等しいという前提が満たされていない．１．の検定方法を使う時には，両群の分散が等しいという前提条件が必須だから，同じ
Student t
検定を行うことができない．「両群の分散」が等しいという帰無仮説を検定するには
F 検定を利用する：

\[
\begin{aligned}
F & = \frac{S^2_A}{S^2_B} \\
  & = \frac{0.21^2}{0.10^2} \\
  & = 4.41
\end{aligned}
\]

自由度 (degree of freedom)はそれぞれ
\(n_A - 1 = 49; n_B -2 = 149\)，P値の計算は EZR を利用する：

\begin{Shaded}
\begin{Highlighting}[]
\DecValTok{2}\OperatorTok{*}\KeywordTok{pf}\NormalTok{(}\FloatTok{4.41}\NormalTok{, }\DecValTok{49}\NormalTok{, }\DecValTok{149}\NormalTok{, }\DataTypeTok{lower.tail =} \OtherTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2.971758e-12
\end{verbatim}

\begin{center}\includegraphics[width=0.9\linewidth]{pic/ftest} \end{center}
\bigskip

以下のコードをRスクリプトに入力して，実行をクリックしてください．自分の検定結果とは一致するかを確認してください．

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{source}\NormalTok{(}\StringTok{"http://aoki2.si.gunma-u.ac.jp/R/src/my_var_test.R"}\NormalTok{, }\DataTypeTok{encoding=}\StringTok{"euc-jp"}\NormalTok{)}
\KeywordTok{my.var.test}\NormalTok{(}\DecValTok{50}\NormalTok{, }\FloatTok{0.21}\OperatorTok{^}\DecValTok{2}\NormalTok{, }\DecValTok{150}\NormalTok{, }\FloatTok{0.1}\OperatorTok{^}\DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  二次データから，二群の等分散性の検定
## 
## data:  n1 = 50, variance1 = 0.0441, n2 = 150, variance2 = 0.01
## F = 4.41, num df = 49, denom df = 149, p-value = 2.972e-12
\end{verbatim}

\begin{center}\includegraphics[width=0.9\linewidth]{pic/ftest01} \end{center}
\bigskip

\underline{手で計算した結果とは一致していると確認できる．}

この検定結果は「両群の脳萎縮度の分散が等しい」という帰無仮説を棄却するために非常に強い証拠を提供したと言える．

There is strong evidence against the null hypothesis that the variances
of atrophy are the same in the two groups.

\newpage
\vfill

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  2.の結果を踏まえて，帰無仮設「両群の脳萎縮度の平均値が等しい」を検定せよ．なお，両群の分散が等しいという前提が満たされていない時に，自由度(df)の計算式は以下となる：
\end{enumerate}

\begin{equation}
\label{eq:2}
\mathbf{df} = \frac{(S^2_A/n_A + S^2_B/n_B)^2}{(S_A^2/n_A)^2/(n_A-1)+(S_B^2/n_B)^2/(n_B-1)}
\end{equation}

また，EZR で t 値，自由度 (df)を使って P
値を計算する時，以下のコマンドを利用してください：

\begin{Shaded}
\begin{Highlighting}[]
\DecValTok{2}\OperatorTok{*}\KeywordTok{pt}\NormalTok{(t value, df, }\DataTypeTok{lower=}\OtherTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\hypertarget{-2}{%
\subsection{答え}\label{-2}}

2.の検定結果から，「両群の脳萎縮度の分散が等しい」という帰無仮説を棄却されたため，Welch
の t 検定を採用する．

\[
\begin{aligned}
\Rightarrow\;\; T & = \frac{\bar{X}_A - \bar{X}_B}{\sqrt{S^2_A/n_A + S^2_B/n_B}} \\ 
                  & = \frac{0.67 - 0.23}{\sqrt{0.21^2/50 + 0.10^2/150}} \\ 
                  & = \frac{0.44}{\sqrt{0.0009486667}} = 14.28551
\end{aligned}
\]

自由度は公式(\ref{eq:2})により計算できる：

\[
\begin{aligned}
\mathbf{df} & = \frac{(S^2_A/n_A + S^2_B/n_B)^2}{(S_A^2/n_A)^2/(n_A-1)+(S_B^2/n_B)^2/(n_B-1)} \\
            & = \frac{(0.21^2/50 + 0.10^2/150)^2}{(0.21^2/50)^2/(50-1)+(0.10^2/150)^2/(150-1)} \\
            & = 58.58105
\end{aligned}
\] P値の計算は EZR を利用する：

\begin{Shaded}
\begin{Highlighting}[]
\DecValTok{2}\OperatorTok{*}\KeywordTok{pt}\NormalTok{(}\FloatTok{14.28551}\NormalTok{, }\FloatTok{58.58105}\NormalTok{, }\DataTypeTok{lower=}\OtherTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 9.601543e-21
\end{verbatim}

\begin{center}\includegraphics[width=0.9\linewidth]{pic/tvaluepvalue01} \end{center}
\bigskip

以下のコードをRスクリプトに入力して，実行をクリックしてください．自分の検定結果とは一致するかを確認してください．

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{source}\NormalTok{(}\StringTok{"http://aoki2.si.gunma-u.ac.jp/R/src/my_t_test.R"}\NormalTok{, }\DataTypeTok{encoding=}\StringTok{"euc-jp"}\NormalTok{)}
\KeywordTok{my.t.test}\NormalTok{(}\DecValTok{50}\NormalTok{, }\FloatTok{0.67}\NormalTok{, }\FloatTok{0.21}\OperatorTok{^}\DecValTok{2}\NormalTok{, }\DecValTok{150}\NormalTok{, }\FloatTok{0.23}\NormalTok{, }\FloatTok{0.10}\OperatorTok{^}\DecValTok{2}\NormalTok{, }\DataTypeTok{var.equal=}\OtherTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  ウエルチの方法による，二群の平均値の差の検定
## 
## data:  
## n1 = 50, mean1 = 0.67, variance1 = 0.0441
## n2 = 150, mean2 = 0.23, variance2 = 0.01
## t = 14.286, df = 56.581, p-value < 2.2e-16
\end{verbatim}

\begin{center}\includegraphics[width=0.9\linewidth]{pic/myttest02} \end{center}
\bigskip

\underline{手で計算した結果とは一致していると確認できる．}

この検定結果は「両群の脳萎縮度の平均値が等しい」という帰無仮説を棄却するために非常に強い証拠を提供したと言える．

There is strong evidence against the null hypothesis that the means of
atrophy are the same in the two groups.

\newpage
\vfill

\section{問題２：線形回帰モデル}

190名の乳幼児の性別（1 = 男，2 = 女），年齢 (月,
months)，体重（kg）のデータを収集した．このデータを用いで，以下の問題を解答したい：

\begin{itemize}
\item
  子供の年齢が一ヶ月の増加によって，体重はどれぐらい増えているか？
\item
  男の子は女の子と比べて，平均的に体重はどれぐらい大きい/小さい？
\end{itemize}

\subsection{データのインポート}

\subsubsection{ステップ １}

\begin{center}\includegraphics[width=0.5\linewidth]{pic/import00} \end{center}

\hypertarget{-1}{%
\subsubsection{ステップ２}\label{-1}}

\begin{center}\includegraphics[width=0.5\linewidth]{pic/import02} \end{center}

\hypertarget{-2}{%
\subsubsection{ステップ３}\label{-2}}

\begin{center}\includegraphics[width=0.7\linewidth]{pic/import03} \end{center}

\hypertarget{-3}{%
\subsubsection{ステップ４}\label{-3}}

\begin{center}\includegraphics[width=0.5\linewidth]{pic/import04} \end{center}

\hypertarget{-4}{%
\subsubsection{ステップ５}\label{-4}}

\begin{center}\includegraphics[width=0.15\linewidth]{pic/import05} \end{center}

\subsection{体重と年齢の散布図，性別により体重の箱ひげ図}

\begin{center}\includegraphics[width=0.85\linewidth]{pic/scatter00} \end{center}

上記左のグラフを描くため，以下のコードをRスクリプトに入力して，実行をクリックしてください．

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(Dataset}\OperatorTok{$}\NormalTok{age,Dataset}\OperatorTok{$}\NormalTok{wt, }
     \DataTypeTok{xlab =} \StringTok{"年齢 (months)"}\NormalTok{, }\DataTypeTok{ylab =} \StringTok{"体重 (kg)"}\NormalTok{,}
     \DataTypeTok{main =} \StringTok{"体重と年齢の散布図"}\NormalTok{,}
     \DataTypeTok{ylim =} \KeywordTok{c}\NormalTok{(}\DecValTok{3}\NormalTok{, }\DecValTok{20}\NormalTok{), }\DataTypeTok{pch=}\KeywordTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\bigskip

\begin{center}\includegraphics[width=0.8\linewidth]{pic/scatter01} \end{center}

\newpage
\vfill

性別により体重の箱ひげ図を描くため，以下のコードをRスクリプトに入力して，実行をクリックしてください．

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{boxplot}\NormalTok{(Dataset}\OperatorTok{$}\NormalTok{wt }\OperatorTok{~}\StringTok{ }\NormalTok{Dataset}\OperatorTok{$}\NormalTok{sex, }\DataTypeTok{ylim =} \KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{18}\NormalTok{),}
        \DataTypeTok{main =} \StringTok{"体重と年齢"}\NormalTok{, }\DataTypeTok{xlab =} \StringTok{"性別"}\NormalTok{, }\DataTypeTok{ylab =} \StringTok{"体重 (kg)"}\NormalTok{,}
        \DataTypeTok{col =} \StringTok{"green"}\NormalTok{, }\DataTypeTok{names =} \KeywordTok{c}\NormalTok{(}\StringTok{"男性"}\NormalTok{, }\StringTok{"女性"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics[width=0.8\linewidth]{pic/box01} \end{center}

\hypertarget{ezr-mean--cor1-2-}{%
\subsection{\texorpdfstring{年齢，体重それぞれの平均値，分散を求めよ；また，年齢と体重の相関係数を算出せよ．なお，EZRで計量データの平均値を計算するには，コマンド
\texttt{mean(変数名)} を使う；共分散を計算したい時に，コマンド
\texttt{cor(変数1,\ 変数2)}
を利用する．}{年齢，体重それぞれの平均値，分散を求めよ；また，年齢と体重の相関係数を算出せよ．なお，EZRで計量データの平均値を計算するには，コマンド mean(変数名) を使う；共分散を計算したい時に，コマンド cor(変数1, 変数2) を利用する．}}\label{ezr-mean--cor1-2-}}

以下のコードをRスクリプトに入力して,実行をクリックしてください．(結果を下の余白に記入すること)

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# 年齢の平均値}
\KeywordTok{mean}\NormalTok{(Dataset}\OperatorTok{$}\NormalTok{age)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 16.97895
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# 年齢の分散}
\KeywordTok{var}\NormalTok{(Dataset}\OperatorTok{$}\NormalTok{age)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 69.5022
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# 体重の平均値}
\KeywordTok{mean}\NormalTok{(Dataset}\OperatorTok{$}\NormalTok{wt)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 9.644737
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# 体重の分散}
\KeywordTok{var}\NormalTok{(Dataset}\OperatorTok{$}\NormalTok{wt)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 3.513068
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# 体重と年齢の共分散 covariance}
\KeywordTok{cov}\NormalTok{(Dataset}\OperatorTok{$}\NormalTok{wt, Dataset}\OperatorTok{$}\NormalTok{age)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 11.49089
\end{verbatim}

\hypertarget{barx--x-}{%
\subsection{\texorpdfstring{年齢を説明変数，体重を目的変数とする場合，年齢の傾き(回帰係数)，と切片を求めよ．なお，分散と共分散の定義を以下とする，\(\bar{X}\)
は \(X\)
の平均値を示す：}{年齢を説明変数，体重を目的変数とする場合，年齢の傾き(回帰係数)，と切片を求めよ．なお，分散と共分散の定義を以下とする，\textbackslash{}bar\{X\} は X の平均値を示す：}}\label{barx--x-}}

\begin{itemize}
\tightlist
\item
  分散 variance:
\end{itemize}

\[
\begin{aligned}
\mathbf{Var}(X) & = \frac{(X_1-\bar{X})^2+(X_2-\bar{X})^2+\cdots+(X_n-\bar{X})^2}{n - 1} \\
                & = \frac{\sum_{i=1}^n(X_i-\bar{X})^2}{n -1}
\end{aligned}
\]

\begin{itemize}
\tightlist
\item
  共分散 covariance:
\end{itemize}

\[
\begin{aligned}
\mathbf{Cov}(X, Y) & = \frac{(X_1 - \bar{X})(Y_1-\bar{Y}) + (X_2 - \bar{X})(Y_2-\bar{Y}) + \cdots + (X_n - \bar{X})(Y_n-\bar{Y})}{n - 1} \\
                   & = \frac{\sum_{i = 1}^n(X_i - \bar{X})(Y_i-\bar{Y})}{n - 1}
\end{aligned}
\]

以下のコードをRスクリプトに入力して,実行をクリックしてください．（結果を下の余白に記入すること）

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# 傾き (slope)}
\NormalTok{beta <-}\StringTok{ }\KeywordTok{cov}\NormalTok{(Dataset}\OperatorTok{$}\NormalTok{wt, Dataset}\OperatorTok{$}\NormalTok{age) }\OperatorTok{/}\StringTok{ }\KeywordTok{var}\NormalTok{(Dataset}\OperatorTok{$}\NormalTok{age)}
\NormalTok{beta}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.1653314
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# 切片 (intercept)}
\NormalTok{alpha <-}\StringTok{ }\KeywordTok{mean}\NormalTok{(Dataset}\OperatorTok{$}\NormalTok{wt) }\OperatorTok{-}\StringTok{ }\KeywordTok{mean}\NormalTok{(Dataset}\OperatorTok{$}\NormalTok{age)}\OperatorTok{*}\NormalTok{beta}
\NormalTok{alpha}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 6.837584
\end{verbatim}

\begin{center}\includegraphics[width=0.75\linewidth]{pic/betaalpha} \end{center}

\hypertarget{ezr}{%
\subsection{実際にEZRで線形モデルを作って見よう：}\label{ezr}}

\hypertarget{-5}{%
\subsubsection{ステップ１}\label{-5}}

\begin{center}\includegraphics[width=0.8\linewidth]{pic/lm00} \end{center}

\hypertarget{-6}{%
\subsubsection{ステップ２}\label{-6}}

\begin{center}\includegraphics[width=0.6\linewidth]{pic/lm01} \end{center}

\hypertarget{-7}{%
\subsubsection{ステップ３}\label{-7}}

\begin{center}\includegraphics[width=0.8\linewidth]{pic/lm02} \end{center}

自分の計算結果とは一致するかを確認してください．

\subsection{今まで計算した傾きと切片の数字を用いて，年齢と体重の関係を線形と考える場合の計算式を記入せよ．傾きと切片の計算結果の意味をそれぞれ記述せよ．}

\hypertarget{-3}{%
\subsubsection{答え}\label{-3}}

\[
Y = 6.838 + 0.165 X
\]

\begin{itemize}
\tightlist
\item
  \(Y:\) 体重 (kg)；
\item
  \(X:\) 年齢 (months)；
\item
  \(0.165:\) 子供の年齢が1ヶ月伸びると，体重が平均的 0.165 kg (165 g)
  高くなる；
\item
  \(6.838:\) 子供の年齢が0ヶ月の時に，体重の平均値は 6.838 kg．
\end{itemize}

\newpage
\vfill

\subsection{性別を説明変数に入れたモデルを作る}

\hypertarget{-factor-}{%
\subsubsection{性別変数を因子 (factor) に変換する}\label{-factor-}}

\hypertarget{-8}{%
\paragraph{ステップ１}\label{-8}}

\begin{center}\includegraphics[width=0.8\linewidth]{pic/sexfactor00} \end{center}

\hypertarget{-9}{%
\paragraph{ステップ２}\label{-9}}

\begin{center}\includegraphics[width=0.4\linewidth]{pic/sexfactor01} \end{center}

\hypertarget{-10}{%
\paragraph{ステップ３}\label{-10}}

\begin{center}\includegraphics[width=0.15\linewidth]{pic/sexfactor02} \end{center}

\paragraph{ステップ４--水準名に男性，女性を入力する}

\begin{center}\includegraphics[width=0.15\linewidth]{pic/sexfactor03} \end{center}

\subsubsection{重回帰線形モデルを作る}

\hypertarget{-11}{%
\paragraph{ステップ１}\label{-11}}

\begin{center}\includegraphics[width=0.8\linewidth]{pic/lm00} \end{center}
\bigskip
\bigskip
\bigskip

\hypertarget{-control-}{%
\paragraph{ステップ２---複数の説明変数を選択する時に control
キーを押しながらマウスで変数名をクリックする}\label{-control-}}

\begin{center}\includegraphics[width=0.4\linewidth]{pic/lm04} \end{center}

\newpage
\vfill

\subsubsection{重回帰線形モデルの結果を確認する}

\begin{center}\includegraphics[width=0.8\linewidth]{pic/lm05} \end{center}

\subsection{重回帰線形モデルの計算結果を用いて，体重の平均値を年齢と性別の線形モデルで表示せよ．各回帰係数の意味を説明せよ．}

\hypertarget{-4}{%
\subsection{答え}\label{-4}}

\[
Y = 7.152 + 0.164 X_1 - 0.519X_2
\]

\begin{itemize}
\tightlist
\item
  \(Y:\) 体重(kg)；
\item
  \(X_1:\) 年齢 (months)；
\item
  \(X_2 = 1:\) 女性；
\item
  \(X_2 = 0:\) 男性；
\item
  \(7.152:\) 男の子が年齢 0 ヶ月の時の平均体重；
\item
  \(0.164:\)
  同じ性別の子供の年齢が1ヶ月高くなることによって，体重が平均的に 0.164
  kg増える；
\item
  \(-0.519:\) 子供年齢が同じ時に，女の子は男の子と比べ，体重が平均的に
  0.519 kg低い．
\end{itemize}

\newpage
\vfill

\hypertarget{34}{%
\subsection{上記の重回帰線形モデルを用いて，年齢が34ヶ月の女の子の体重の予測値を計算せよ．}\label{34}}

\hypertarget{-5}{%
\subsection{答え}\label{-5}}

\begin{itemize}
\tightlist
\item
  \(X_1 = 34\)；
\item
  \(X_2 = 1\);
\end{itemize}

\[
\begin{aligned}
Y & = 7.152 + 0.164 \times 34 -0.519\times 1 \\
  & = 12.209\; \mathbf{(kg)}
\end{aligned}
\]

\bigskip\bigskip\bigskip\bigskip\bigskip\bigskip

\subsection{男女別の年齢と体重の散布図を描く}

\bigskip\bigskip\bigskip\bigskip\bigskip\bigskip

\begin{center}\includegraphics[width=0.6\linewidth]{pic/scatter02} \end{center}

\hypertarget{-12}{%
\subsubsection{ステップ１}\label{-12}}

\begin{center}\includegraphics[width=0.5\linewidth,height=0.5\textheight]{pic/scatter03} \end{center}

\hypertarget{-13}{%
\subsubsection{ステップ２}\label{-13}}

\begin{center}\includegraphics[width=0.4\linewidth]{pic/scatter04} \end{center}

\hypertarget{-14}{%
\subsubsection{ステップ３}\label{-14}}

\begin{center}\includegraphics[width=0.25\linewidth]{pic/scatter05} \end{center}

\hypertarget{-15}{%
\subsubsection{ステップ４}\label{-15}}

\begin{center}\includegraphics[width=0.5\linewidth]{pic/scatter06} \end{center}

\hypertarget{-16}{%
\subsubsection{ステップ５}\label{-16}}

\begin{center}\includegraphics[width=0.25\linewidth]{pic/scatter07} \end{center}

\hypertarget{chi2-}{%
\section{\texorpdfstring{問題３：\(\chi^2\)
検定，オッズ比，ロジスティクス回帰モデル}{問題３：\textbackslash{}chi\^{}2 検定，オッズ比，ロジスティクス回帰モデル}}\label{chi2-}}

1990年代，アフリカナイジェリア北部でオンコセルカ症 (回旋糸状虫症,
onchocerciasis; river blindness とも呼ばれる)
が流行していた．ある研究チームが流行していた地域の34個の村に住む15歳以上の全住民に目の検査を行った．目の検査受けた住民はWHOの診断基準を元に，「視覚障害
(visually impaired)」と「視力正常 (normal
vision」に分類された．対象者を三年間観察され，その期間中に死亡者を登録された．

\subsection{視覚障害と死亡の関係}

視覚障害の有無と死亡リスクの関連を見るために，以下の表をまとめた：

\begin{center}
\begin{tabular}{|c|c|c|c|}
\hline
死亡 & 視力正常           & 視覚障害          & 合計             \\ \hline
0  & 3874 (97.56\%) & 287 (87.77\%) & 4161 (96.81\%) \\ \hline
1  & 97 (2.44\%)    & 40 (12.23\%)  & 137 (3.19\%)   \\ \hline
合計 & 3971 (100\%)   & 327 (100\%)   & 4298 (100\%)   \\ \hline
\end{tabular}
\end{center}

\subsubsection{もし，視覚障害と対象者の死亡リスクと関連がない場合，下の表（各セルの期待者数）を入力せよ：}

\begin{center}
\begin{tabular}{|c|c|c|c|}
\hline
死亡 & 視力正常                     & 視覚障害                   & 合計             \\ \hline
0  & 3971$\times$4161/4298 = 3844.4232 & 327$\times$4161/4298 = 316.5768 & 4161 (96.81\%) \\ \hline
1  & 3971$\times$137/4298 = 126.5768   & 327$\times$173/4298 = 10.4232   & 137 (3.19\%)   \\ \hline
合計 & 3971 (100\%)             & 327 (100\%)            & 4298 (100\%)   \\ \hline
\end{tabular}
\end{center}

\hypertarget{-chi2-}{%
\subsubsection{\texorpdfstring{上記の２つの表の数字を使って \(\chi^2\)
統計量を計算せよ}{上記の２つの表の数字を使って \textbackslash{}chi\^{}2 統計量を計算せよ}}\label{-chi2-}}

\hypertarget{-6}{%
\subsubsection{答え}\label{-6}}

\[
\begin{aligned}
\chi^2 & = \frac{(3874 - 3844.4232)^2}{3844.4232} + \frac{(287 - 316.5768)^2}{316.5768} + \frac{(97 - 126.5768)^2}{126.5768} + \frac{(40 - 10.4232)^2}{10.4232} \\
       & = 93.829
\end{aligned}
\]

\hypertarget{times-2--2-1times2-1-1}{%
\subsubsection{\texorpdfstring{2 \(\times\) 2 の分割表では，自由度は
\((2-1)\times(2-1) = 1\)
．}{2 \textbackslash{}times 2 の分割表では，自由度は (2-1)\textbackslash{}times(2-1) = 1 ．}}\label{times-2--2-1times2-1-1}}

EZRで，\(\chi^2\)統計量と自由度(df)を使って P
値を計算したい場合，以下のコマンドが利用できる：

\begin{Shaded}
\begin{Highlighting}[]
\DecValTok{2}\OperatorTok{*}\KeywordTok{pchisq}\NormalTok{(chisquare統計量, df, }\DataTypeTok{lower =} \OtherTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\DecValTok{2}\OperatorTok{*}\KeywordTok{pchisq}\NormalTok{(}\FloatTok{93.829}\NormalTok{, }\DecValTok{1}\NormalTok{, }\DataTypeTok{lower =} \OtherTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 6.879894e-22
\end{verbatim}

\begin{center}\includegraphics[width=0.7\linewidth]{pic/mychisqtest02} \end{center}

以下のコードをRスクリプトに入力して,実行をクリックしてください.自分の検定結果とは一致するかを確認し
てください.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{source}\NormalTok{(}\StringTok{"http://aoki2.si.gunma-u.ac.jp/R/src/my-chisq-test.R"}\NormalTok{, }\DataTypeTok{encoding=}\StringTok{"euc-jp"}\NormalTok{)}
\NormalTok{a <-}\StringTok{ }\KeywordTok{my.chisq.test}\NormalTok{(}\KeywordTok{matrix}\NormalTok{(}\KeywordTok{c}\NormalTok{(}\DecValTok{3874}\NormalTok{, }\DecValTok{97}\NormalTok{, }\DecValTok{287}\NormalTok{, }\DecValTok{40}\NormalTok{), }\DataTypeTok{nrow =} \DecValTok{2}\NormalTok{))}
\NormalTok{a}\OperatorTok{$}\NormalTok{expected }\CommentTok{# 期待者数表}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##           [,1]      [,2]
## [1,] 3844.4232 316.57678
## [2,]  126.5768  10.42322
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{a}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  カイ二乗分布を用いる独立性の検定（残差分析）
## 
## data:  matrix(c(3874, 97, 287, 40), nrow = 2)
## X-squared = 93.829, df = 1, p-value < 2.2e-16
\end{verbatim}

\begin{center}\includegraphics[width=0.8\linewidth]{pic/mychisqtest01} \end{center}

\underline{手で計算した結果とは一致していると確認できる．}

この検定結果は「視覚障害と対象者の死亡リスクと関連がない」という帰無仮説を棄却するために非常に強い証拠を提供したと言える．
(There is strong evidence against the null hypothesis that there is no
association between visual impairment and risk of death.)

\newpage
\vfill

\subsubsection{視覚障害と死亡の関係を示すテーブルの数を元に，下表を完成せよ：}

\begin{center}
\begin{tabular}{|c|c|c|c|}
\hline
                 & 視力正常   & 視覚障害    & トータル   \\ \hline
リスク (risk)       & 0.0244 & 0.1223  & 0.0319 \\ \hline
オッズ (odds)       & 0.0250 & 0.1394  & 0.0329 \\ \hline
対数オッズ (log-odds) & -3.689 & -1.9704 & -3.414 \\ \hline
\end{tabular}
\end{center}

\bigskip

では，視覚障害者と死亡の関連を示すオッズ比は：

\[
\mathbf{OR} = 0.1394 \div 0.025 = 5.576
\]

このオッズ比の対数を取った値 \(\mathbf{log(OR)}\) は：

\[
\mathbf{log(OR)} = 1.717
\]

\hypertarget{ezr}{%
\subsubsection{EZRでロジスティクス回帰モデルを作る}\label{ezr}}

\hypertarget{-}{%
\paragraph{ステップ１ --- データのインポート}\label{-}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
\end{enumerate}

\begin{center}\includegraphics[width=0.5\linewidth]{pic/import00} \end{center}

\newpage
\vfill

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\item
\end{enumerate}

\begin{center}\includegraphics[width=0.3\linewidth]{pic/logstic01} \end{center}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\item
\end{enumerate}

\begin{center}\includegraphics[width=0.7\linewidth]{pic/logstic02} \end{center}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{3}
\item
\end{enumerate}

\begin{center}\includegraphics[width=0.7\linewidth]{pic/logstic03} \end{center}

\newpage
\vfill

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{4}
\item
\end{enumerate}

\begin{center}\includegraphics[width=0.7\linewidth]{pic/logstic04} \end{center}

\hypertarget{-}{%
\paragraph{ステップ２ --- ロジスティクスモデルを作る}\label{-}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{5}
\item
\end{enumerate}

\begin{center}\includegraphics[width=0.8\textwidth,height=0.9\textwidth]{pic/logstic05} \end{center}

\newpage
\vfill

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{6}
\item
\end{enumerate}

\begin{center}\includegraphics[width=0.5\linewidth]{pic/logstic06} \end{center}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{7}
\item
\end{enumerate}

\begin{center}\includegraphics[width=0.5\linewidth]{pic/logstic07} \end{center}

\newpage
\vfill

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{8}
\item
\end{enumerate}

\begin{center}\includegraphics[width=0.55\linewidth]{pic/logstic08} \end{center}

計算したオッズ比はここの結果とは一致しているかを確認してください．

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{9}
\item
\end{enumerate}

\begin{center}\includegraphics[width=0.55\linewidth]{pic/logstic09} \end{center}

\begin{itemize}
\tightlist
\item
  (intercept/切片) の \texttt{-3.689}
  は''視力正常''群の対数オッズであることを確認できる；
\item
  \texttt{vimp} (視覚障害)の回帰係数 \texttt{1.7167}
  は''視覚障害''と''視力正常''群に比べた log(OR) = log(odds in 視覚障害)
  - log(odds in 視力正常) = -1.9704 - (-3.689)である．
\end{itemize}

\subsection{年齢の影響を考慮する}

\begin{center}
\begin{tabular}{|c|c|c|c|c|c|c|c|c|c|c|}
\hline
       & \multicolumn{10}{c|}{視覚障害 (0 = no, 1 = yes)}                                                                                                  \\ \hline
死亡     & 0             & 1          & 0            & 1           & 0            & 1           & 0           & 1           & 0            & 1           \\ \hline
1 = yes & 29            & 2          & 38           & 10          & 15           & 11          & 15          & 17          & 97           & 40          \\ \hline
0 = no & 2301          & 22         & 1271         & 124         & 212          & 69          & 90          & 72          & 3874         & 287         \\ \hline
  n     & 2330          &  24         & 1309         & 134         & 227          & 80          & 105          & 89          & 3971         & 327         \\ \hline
年齢     & \multicolumn{2}{c|}{15-34} & \multicolumn{2}{c|}{35-54} & \multicolumn{2}{c|}{55-64} & \multicolumn{2}{c|}{65 +} & \multicolumn{2}{c|}{Total} \\ \hline
\end{tabular}
\end{center}

上記のデータをよく見ると，視覚障害のオッズは年齢と共に上昇している
(年齢が15-34歳群の\((2 + 22) / (29 + 2301) = 0.010\)から年齢が65歳以上群の\((17+72)/(15+90) = 0.848\)に上げた)．しかし，年齢の上昇と共に，死亡のオッズも上がる．年齢はここで，\underline{交絡因子 (confounder) }と定義される．

\subsubsection{以上のデータと解説をよく理解した上で，下表を完成せよ：}

\begin{center}
\begin{tabular}{|c|c|c|c|}
\hline
      & \multicolumn{2}{c|}{オッズ}    &        \\ \hline
年齢    & 視力正常              & 視覚障害    & オッズ比   \\ \hline
15-34 & 29/2301 = 0.01260 & 0.0909  & 7.214  \\ \hline
35-54 & 0.02990           & 0.08065 & 2.6973 \\ \hline
55-64 & 0.07075           & 0.15942 & 2.2533 \\ \hline
65+   & 0.16667           & 0.23611 & 1.4166 \\ \hline
\end{tabular}
\end{center}

\hypertarget{ezr}{%
\subsubsection{EZRで年齢グループを調整したロジスティクス回帰モデルを作る}\label{ezr}}

\hypertarget{-agegrp--factor-}{%
\paragraph{\texorpdfstring{年齢グループ \texttt{agegrp} 変数を因子
(factor)
に変換する}{年齢グループ agegrp 変数を因子 (factor) に変換する}}\label{-agegrp--factor-}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
\end{enumerate}

\begin{center}\includegraphics[width=0.55\linewidth,height=0.5\textheight]{pic/mltlogstic00} \end{center}

\newpage
\vfill

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\item
\end{enumerate}

\begin{center}\includegraphics[width=0.55\linewidth,height=0.5\textheight]{pic/mltlogstic01} \end{center}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\item
\end{enumerate}

\begin{center}\includegraphics[width=0.3\linewidth,height=0.5\textheight]{pic/mltlogstic02} \end{center}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{3}
\tightlist
\item
  水準名に各年齢グループの名前を入力する
\end{enumerate}

\begin{center}\includegraphics[width=0.3\linewidth,height=0.5\textheight]{pic/mltlogstic03} \end{center}

\newpage
\vfill

\paragraph{多変量ロジスティクス回帰モデルを作る}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
\end{enumerate}

\begin{center}\includegraphics[width=0.8\linewidth,height=0.5\textheight]{pic/mltlogstic04} \end{center}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  \texttt{agegrp} が因子になったことが確認できる．\newline \texttt{died}
  (死亡) を目的変数へ，\texttt{vimp} (視覚障害) を説明変数へ
\end{enumerate}

\begin{center}\includegraphics[width=0.5\linewidth,height=0.5\textheight]{pic/mltlogstic05} \end{center}

\newpage
\vfill

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  \texttt{agegrp} も目的変数へ移動すると自動的に \texttt{+}
  が入れられる．OKをクリックする．
\end{enumerate}

\begin{center}\includegraphics[width=0.5\linewidth,height=0.5\textheight]{pic/mltlogstic06} \end{center}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{3}
\tightlist
\item
  視覚障害と死亡の関係を評価する年齢調整オッズ比が計算される．
\end{enumerate}

\begin{center}\includegraphics[width=0.5\linewidth,height=0.5\textheight]{pic/mltlogstic07} \end{center}

\hypertarget{-crude-odds-ratio-}{%
\paragraph{単変量ロジスティクス回帰モデルで評価した粗オッズ比 (crude
odds ratio)
と比べ，年齢調整オッズ比はどう変わったかを説明せよ．}\label{-crude-odds-ratio-}}

\hypertarget{-7}{%
\paragraph{答え}\label{-7}}

年齢を考慮していない場合，視覚障害者は視力正常者と比べ，三年間の間に死亡するオッズが5.57倍であり，95\%信頼区間が
3.78 - 8.20 と推定される．

多変量ロジスティクス回帰モデルを用いて，視覚障害と死亡の関係に年齢の交絡考慮した後，オッズ比が
2.20 になり，95\%信頼区間が 1.41 - 3.44
と推定される．このオッズ比が大きく変化した（小さくなった）ことは，年齢がこの関連の強い交絡因子であることを示唆される．また，年齢調整したオッズ比の95\%信頼区間は
1
を跨いでいない．以上の結果を踏まえて，「視覚障害者は視力正常者と比べ，観察期間中に死亡するオッズが有意に高いこと」を支持するために，非常に強い証拠を提供した．

(なお，この解析は，「各年齢層内の視覚障害と死亡の関係が等しい」という前提が仮定される．つまり，2.20は各年齢層の視覚障害と死亡の関係を評価する共通オッズ比
{[}common odds ratio{]} である．)

\newpage
\vfill

\section{問題４：生存分析}

\newpage
\vfill

\section{参考図書：}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  中澤　港，「Rによる保健医療データ解析演習」，（\url{http://minato.sip21c.org/msb/medstatbookx.pdf}）
\item
  新谷　歩，「みんなの医療統計 12日間で基礎理論とEZRを完全マスター!」．
\end{enumerate}


\end{document}
